export const defaultTheme = {
  colorBlackForText: "#333333",
  colorWhite: "#ffffff",
  colorForLightBackground: "#d8ecfe",
  backgroundCatalog: "#f6f6f6",
  colorForFermIcon: "#ffb334",
  colorForMarketIcon: "#88AA4D",
  backgroundForFermCard: "#e1edce",
  backgroundForMarketCard: "#f8ddd7",
  colorForButton: "#fc9b27",
  colorForButtonHover: "#fc7427",
  pagePadding: "90px",
  indent: "20px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  lineHeightDefault: 1.5,
  headerHeight: "80px",
  footerHeight: "80px",
  pageWidth: "1280px",
};
